# Generated by Django 4.0.2 on 2023-12-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=50)),
                ('track', models.CharField(max_length=50)),
                ('qualilaptime', models.CharField(max_length=20, null=True)),
                ('racelaptime', models.CharField(max_length=20, null=True)),
                ('thumbnailName', models.CharField(max_length=50)),
                ('interests', models.IntegerField(default=0)),
                ('setsbaseLink', models.CharField(max_length=100, null=True)),
                ('popometerLink', models.CharField(max_length=100, null=True)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='setupnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteName', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('thumbnailName', models.CharField(max_length=50)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setupsmanager.carsetup')),
            ],
        ),
    ]
