# Generated by Django 4.0.2 on 2024-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupsmanager', '0003_alter_setupnote_notename'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupnote',
            name='trackLocation',
            field=models.CharField(default='all track', max_length=50),
        ),
    ]
