# Generated by Django 4.0.2 on 2022-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userManagement', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(default='ManualInput', max_length=80),
        ),
    ]
