# Generated by Django 4.0.2 on 2022-07-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userManagement', '0004_alter_user_managers_remove_user_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
