# Generated by Django 4.0.2 on 2022-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userManagement', '0005_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
