# Generated by Django 4.0.2 on 2022-07-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userManagement', '0008_user_verficationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verficationcode',
            new_name='verificationcode',
        ),
    ]
